{{/* applications/stack-chart/templates/frontend-service.yaml */}}
{{- $ctx := dict "Release" .Release "Chart" .Chart "component" .Values.frontend.name -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "stack-chart.fullname" $ctx }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stack-chart.labels" $ctx | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "stack-chart.selectorLabels" $ctx | nindent 4 }}
