{{/* applications/stack-chart/templates/frontend-deployment.yaml */}}
{{- $ctx := dict "Release" .Release "Chart" .Chart "component" .Values.frontend.name -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "stack-chart.fullname" $ctx }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "stack-chart.labels" $ctx | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "stack-chart.selectorLabels" $ctx | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "stack-chart.selectorLabels" $ctx | nindent 8 }}
    spec:
      containers:
        - name: {{ .Values.frontend.name }}
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
