{{- range $service := .Values.services }}
{{- if and $service.secret (default false $service.secret.enabled) }}
{{- $ctx := dict "Release" $.Release "Chart" $.Chart "component" $service.name -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stack-chart.fullname" $ctx }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "stack-chart.labels" $ctx | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ default "0" $service.syncWave | quote }}
type: Opaque
data:
  {{- range $key, $val := $service.secret.data }}
  {{ $key }}: {{ $val | b64enc | quote }}
  {{- end }}
{{- end }}
{{- end }}
