apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "infrastructure.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWaves.base | quote }}
type: Opaque
data:
  root-password: {{ .Values.mysql.credentials.rootPassword | b64enc | quote }}
  username: {{ .Values.mysql.credentials.username | b64enc | quote }}
  password: {{ .Values.mysql.credentials.password | b64enc | quote }}
  database: {{ .Values.mysql.credentials.database | b64enc | quote }}